"""Add user table

Revision ID: 56be6b074842
Revises:
Create Date: 2025-08-24 19:28:08.124120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56be6b074842"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.Column("first_name", sa.String(), nullable=True, comment="First name"),
        sa.Column("last_name", sa.String(), nullable=True, comment="Last name"),
        sa.Column("email", sa.String(), nullable=False, comment="Email"),
        sa.Column(
            "hashed_password", sa.String(), nullable=True, comment="Hashed password"
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Is active"),
        sa.Column(
            "last_login",
            sa.DateTime(),
            nullable=True,
            comment="Last login",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Created at",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
