"""Add permission table

Revision ID: a4e6e77d1dfe
Revises: 56be6b074842
Create Date: 2025-09-03 14:51:57.355899

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4e6e77d1dfe"
down_revision: Union[str, None] = "56be6b074842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column(
            "role",
            sa.Enum("ADMIN", "SUPPORT", "USER", name="roleenum"),
            nullable=False,
            comment="Role",
        ),
        sa.Column(
            "action",
            sa.Enum("CREATE", "READ", "UPDATE", "DELETE", name="actionenum"),
            nullable=False,
            comment="Action",
        ),
        sa.Column(
            "resource",
            sa.Enum("USER", "PERMISSION", name="resourceenum"),
            nullable=False,
            comment="Resource",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Created at",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated at",
        ),
        sa.PrimaryKeyConstraint("role", "action", "resource"),
    )
    op.create_index(
        "index_role_action_resource",
        "permissions",
        ["role", "action", "resource"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("ADMIN", "SUPPORT", "USER", name="roleenum"),
            nullable=False,
            comment="Role",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated at",
        ),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "role")
    op.drop_index("index_role_action_resource", table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
