"""Add permission is_active

Revision ID: b33d160f4af0
Revises: a4e6e77d1dfe
Create Date: 2025-09-03 16:10:50.010372

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b33d160f4af0"
down_revision: Union[str, None] = "a4e6e77d1dfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions",
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Is active"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permissions", "is_active")
    # ### end Alembic commands ###
